
// div要素を生成
'use strict';

const name_array = [
'佐藤賢志郎',
'中本圭',
'門井丈丸',
'西山 晃人',
'菊地晏南',
'澤田悠太郎',
'佐野由季',
'秀島 宇音',
'西山 晃人',
'鈴木遥登',
'小川 彪（おがわ ひゅう）',
'山下陸',
'中川 紘輔',
'片山峻佑',
'河野 麗',
'山川 凌太郎',
'田岡健太',
'竹内優稀',
'吉田翔',
'進士喜章',
'森 直也',
'片山 育星',
'宮野広基',
'山口祐司',
'小野直樹',
'富木菜穂',
'蔡昱毅',
'落合貴也',
'内藤 壮俊',
'辻啓吾',
'笠西 哲',
'大井元',
'勝瑞雄介',
'高品 剛大',
'下野明佳里',
'寺尾健裕',
'金谷光一郎',
'京野長彦',
'堀 紡希',
'箱田崚',
'近藤 佑亮',
'高橋篤剛',
'船渡勇吾',
'大宮誉史',
'大森拓郎',
'久留陽一郎',
'稲津遥太郎',
'遠藤 達朗',
'岡村京輔',
'竹田慎次朗',
'篠田和宏',
'ピチュカ ヴェンカタ ラマナ',
'河野 翔太',
'柴田彩登',
'藤村柊吾',
'木内陽大',
'邢 明吉(しん あきよし)',
'畠山智之',
'秦竟超',
'藤田航輝',
'鈴木凌斗',
'星 智文',
'髙橋俊',
'澤邉　裕紀',
'ウィジャヤ　テオドルス',
'清水麻琴',
'松藤圭亮',
'髙橋俊',
'上野　爽',
'加藤准也',
'森一馬',
'中本光彦',
'生野駿',
'有井慎平',
'櫻崇史',
'鈴木大智',
'木野山 力隆',
'陳瑞彦',
'関 祐一',
'覚井優希',
'長谷川祐也',
'竹中 毅',
'吉津遼平',
'高城和馬',
'稲津遥太郎',
'宮田寛生',
'鍜治口 結衣',
'浅部 佑',
'新浩太朗',
'高崎環',
'越能俊介',
'阿部浩太郎',
'安斉周',
'阿久井 駿',
'高田 篤志',
'中田惇貴',
'出口裕也',
'荻野 由真',
'吉清 秦生',
'山口 貴史',
'林孝明',
'角南陽人',
'吉田 慎一朗'
];

const nickname_array = [
  'とうふ',
  'けい',
  'ピカチュウ',
  'あっきー',
  'あなん',
  'ベン、おべんくそ、げろ',
  'さのゆき',
  'ひで, Takato Hideshima',
  'あっきー',
  'はると',
  'fiord（ふぃよるど）',
  '',
  'Twitterのアカウント名で呼ばれることが多いです',
  '片山',
  'うらら、うららちゃん',
  '',
  'たおけん',
  'Twitterは「ぺんぎー」です',
  'Ｂ(ちゃん)',
  '特になし',
  '',
  'いかた',
  '',
  'ぶーじ(中高時代ですが)',
  '',
  'なほ、とみき',
  '',
  'おちあい、屋上',
  'そうしゅん',
  '',
  '特になし',
  'げん○○、おおいちゃん',
  'しょーずい、ずい',
  '',
  'あかり',
  '',
  'かなや',
  '',
  '堀、つむつむ',
  '',
  'コンドウナギ、ウナギ、ナギ、こんちゃん、どぅー',
  '',
  'ふなと',
  'なし',
  '',
  'トメさん',
  'ぴなつ、ピーナッツ',
  '',
  '',
  '',
  '',
  'ピチュカ',
  '',
  '柴ちゃん',
  '',
  'きうち',
  'しん(君付けが多い)',
  '',
  '',
  'ふじこー',
  'モジャ',
  '(中学までは「ほっしー」呼びだった)',
  '',
  'べつ',
  'テオ',
  'まこっちゃん',
  'まっちゃん　まっつん',
  '',
  '',
  '',
  '',
  '',
  'のしゅん',
  '慎平',
  'チェリー',
  '鈴木、大ちゃん、石油王、アラブ…etc',
  'きの、リッキー',
  'Ruiyan/チェン',
  '',
  '',
  '長谷川',
  '',
  'りょうへい',
  'たき',
  'ぴなつ、ピーナッツ',
  'ふなっしー',
  'かじぐち',
  '',
  'あらた',
  'めぐる、とかめぐるん、とかですかね',
  'しゅんすけ',
  'あべこー',
  'ざいしゅ',
  '',
  '',
  '',
  'やんぎん',
  '',
  'よしきよ',
  'や◯ち',
  '',
  'ぺち',
  'ぴーよ'
];



const message_array = [
  '名簿を作りました。パ長をしています。趣味は料理と筋トレです。強くなりたい。EEIC最高！！！🕺🕺',
'野球が大好きです。\n1限に行くのが苦手です。\n2限に行くのが苦手です。\n閉館まで図書館にいるのが好きです。\nいつも赤い自転車で移動しています。',
'英文読解が好きです．人間も好きになりたい．',
'色々な呼び方をしていただいてるのであれですが、西山でもあっきーでも好きなように呼んでください！スポーツ全般は好きです！勉強も大好きです〜笑',
'バスケとバレーやってます！eeicのみんなともっと仲良くなりたいです！',
'気軽に話しかけてください！お笑い好きです！麻雀しましょう🀄️',
'eeic同期でもっと仲良くなりたいです！',
'Share your creativity with me.',
'1番好きなことは睡眠です。後はスポーツ全般好きです！特に自分でやるのが好きです！よろしくお願いします！',
'電電／Twitter名:少年H／出身:ラブライブ！サンシャイン!!の聖地沼津／趣味:•サッカー観戦(年間10試合程度)／応援してるチームはジュビロ磐田。サッカーはするのも好き。昔は現J3アスルクラロ沼津の下部組織で県大会優勝経験あり／•ボクシング観戦(年間3興行程度)／サッカーかボクシング好きな人いたら話しましょう‼︎／•気ままに散歩、旅行すること／一人でいるときはぶすっとしてるけど、話せば気さくです！よろしくお願いします！',
'世界初のバーチャルグソクムシです！(GW中に達成予定。出来たらこのコメント消して下さいm(__)m）競プロやったりCTFやったりWebやったり…誰得な情報を垂れ流していきたいと思います！',
'セパタクローやってる人',
'Wake Up, Girls!と高木美佑さんをこよなく愛しています。最近はi☆Ris、TrySail、小倉唯現場にいます。京都市伏見区出身ですが、小学校の時はマレーシアに住んでました。アピールポイントとしては、修学旅行先のマレーシア（再訪）で強盗に襲撃されて応戦し、撃退したことがあります。よろしくお願いします。',
'スマブラとか麻雀好きなのでやりましょう',
'衛星やローバーの設計に興味があります！趣味はダンスです💃',
'写真の通り、生活の大部分がサークルで歌うことに費やされてます／なのでeeic側にはあまりコミットできてないですが、よろしくです🙇‍♂️',
'田岡と申します。運動会水泳部に入っていて、たまに御殿下にいるので一緒にウェイトしましょう！',
'ジャグラー兼ゲームプログラマーです。パズルゲームが好きです',
'東大オケで、ホルン吹いたり執行部やったりしてます。みんなよかったら演奏会来てね！！',
'英語勉強中です。',
'ゲーム、運動、吉岡里帆さんが好きです。対戦よろしくお願いします。',
'音楽を幅広くやっててギターとピアノ弾きます。合気道もやってます。',
'ロボテックで機械を作ってます。電子工作とかものづくりが好きです。他にもF1やアニメ、PCゲーム(FPSとかleague of legendsとか)が趣味です。よろしくお願いします。',
'サークルは、地理部と鉄道研究会、帝虎会(最近行けてません)に入っていて、また今年から丁友会とTtimeにも入りました。現時点では、制御系の研究室に進もうと考えています。よろしくお願いします！',
'絵とか描く可能性があります😉',
'フィロムジカというオーケストラでフルートを吹いてます。演奏会とか来てくれるととても喜びます♪',
'修理屋やってます。困ったことがあればぜひご相談を。',
'たぶんカップル受講の人です笑',
'数学とかプログラミングとかが好きです。ノンリニアでゲーム作ってます。喋るのは結構好きな方だと思う',
'しょうもないことが好き',
'TBAというサークルでバドミントンやってます。もし他にバドしてる人がいれば御殿下とかで一緒に打ちたいです！また鉄道旅行が好きで、夏休みなどによく18きっぷで日本各地を旅してまわっています。これからよろしくお願いします！Twitter: @tetsu9923',
'学科的に全然強くないです。興味はネットワークやIoTあたりにあります。趣味は現在探しています。オススメがあれば教えてください。アニメは2000後半～2010前半の作品、マンガはヒロアカ、黒執事などが好きです。お酒弱々なので飲み会に参加するかいつも迷います。話しかけたとき答えてくれると嬉しいです。よろしくお願いします。',
'ボードゲームやアーケードゲームが好き',
'デレステP',
'鹿児島出身です／音楽とお笑い好きなので好きな方いたら話しかけて下さい:)',
'卓球趣味で、するのも見るのも好きなので趣味が合う方がいたら是非。なろうとかも好きです。インターンを探してるので紹介してもらえるとありがたいですm(__)m',
'クールで天才な絵に描いたようなイケメンがいたら僕だと思ってね。AtCoderやってます。天才なので赤色かもしれないよ。実際は緑だよ。人生辛いーいーあいしーだね。みんながんばろ！',
'信号解析不可ったやつです',
'たまに控室でボードゲームなどしているので一緒にやりましょう☆',
'学科内隅っこ勢なんで声かけてくれるとうれしいです',
'運動会のボディビルアンドウェイトリフティング部に所属しています。一緒に御殿下でトレーニングしましょう！！！プロダクトを作るのに興味があるので、もし何かで人手が足りなければ声をかけてください！！！アニメ大好き！！！',
'回答遅くなってすいません...',
'バスケが好きでよくNBAとか見てます。仲良くしていただけると嬉しいです。',
'愛知県出身で実家は三重県です。中日とか好きです、ハロプロとかも好きです。よろしくお願いします',
'電電ですけどコンピューターの内部とかソフトウェア系に興味があります。よろしくお願いします！',
'甘いもの、アクアリウム、サイクリング、プラモデル、漫画、空手が好きです。寝坊します。出席票回してください。',
'音楽が大大大好き。多重録音ギターピアノアカペラなどやってます。',
'自分で自分自身のことを把握できていないきらいがありますのでご容赦ください。',
'スマブラとか誘ってくれると泣いて喜びます。プログラミング弱者なので任意のプロの方是非お助けを',
'逆立ちとパワプロが好きです',
'Twitter:@kcfnen1916',
'インド人です。',
'小さいころプログラミングもどきをやったことがあり、最近ちゃんとした言語に触れて衝撃を受けました。プログラミングで何か楽しいものを作れたらなあと思っています。',
'アマチュア無線やってます、よろしく',
'バスケと自転車が大好きなわんぱく小僧です！',
'高校でアメフトやってましたー(全然ゴツくないけど)／LGTMっていうエンジニアコミュニティ団体を友達と運営してます！企業に協賛してもらってハッカソンとかやってます！興味あれば声かけてね^ ^',
'プログラミング系はよわよわ(AtCoderチュートリアルしか触ってません)／趣味は謎解き、スプラ／シュタゲは見るべき',
'トランペット吹いてます〜',
'彼女いません。絶賛募集中です。',
'Twitterをやってたりやってなかったりします。あまり言ってないのですが実は競馬がめちゃくちゃ好きで多分学科で1番詳しい自信があります()／よかったら話しかけてください笑',
'家が近いので遊びに来て乁(˙꒳˙乁)ｸﾚﾖ...',
'大体いつもチェックシャツ着てる人です。コミュ障ガチ勢ですが、話しかけられたくない系ではないのでよろしくお願いします。',
'カメラ、ロードバイク、ランニング、イワテ、',
'べつです。生まれてからビデオゲームしかしたことないです。基本的に話しかけられるのは嬉しいので、仲良くしてください。よろしくお願いします。',
'インドネシアから来た留学生。趣味は語源学や読書。昔の曲は現代よりファンキーだと思っている。',
'よわよわだけど頑張りまーすよろしく！',
'この名簿を作ってくれたとうふくんに感謝。いまEEICの中で面識ある人を数えたら50人だった。この名簿をうまく使って、卒業までに全員と知り合えたら／福岡県福岡市出身。幼少時より国内各地を転々とし、今住んでるシェアハウスで10か所目／地図の読み書きを含む活動（鉄道、山歩き、サイクリング...）が大好き。国際地理五輪銀メダリスト／ネイティブではないが中国語ができる。中学時代から勉強していたが、それは中国語の音の美しさに魅かれたからで、特に先見の明があったわけではない。根津の唐揚げ屋さんのメニューを中国語に訳したご縁で、その日の余った唐揚げをいただいている／EEICにやってきたのは、スマホやAIの次には何が来るのかを探すため。レベルの高い同級生たちに必死についていっている／将来は創業し、日本を代表するテクノロジー企業を育てたい。太陽光を人類最大のエネルギー源にしたい／オンラインでの返事が遅いのが課題。鋭意改善中／悩みは現在恋人がいないことくらいで笑、毎日とても幸せに生きている。',
'カメラ、ロードバイク、ランニング、イワテ',
'ラズパイとか制御とかゆる～くやってます',
'資本を蓄積して、学士入学しました',
'体を動かすことが好きです(特にサッカー)',
'圭じゃない方の中本です',
'左後方が指定席',
'高専からの編入です。よろしく。',
'文ニから来ました。オーディオが趣味',
'好きな食べ物はチキンカツとカレーとマシュマロと海苔です。',
'ゲーム、散歩、サイクリング、映画、甘いものなどいろいろ好きです。よろしくお願いします。',
'（人見知り＋顔・方向・運動音痴＋日本語弱）×（趣味音楽＋一応バイオリン上級＋高校の時バンドやってた）＝？',
'ぼちぼち絵描いてます',
'ジャグリングします。',
'よろしくお願いします',
'趣味: アニメ音楽YouTube ',
'週刊少年ジャンプを毎週読んでます。呪術廻戦推しだよ。',
'漫画、小説、アニメ、映画、邦楽、洋楽、バレーボールなど、ここに書ききれないくらい好きなものばかりです。人生楽しいです。よろしくお願いします。',
'音楽が大大大好き。多重録音ギターピアノアカペラなどやってます。',
'授業についていけません。本当に心配です。後、将来もすごく心配です。',
'Twitter @kajiguchi97 です。丁友会皆さんのTwitter垢教えてくださいな。初音ミクが好きです。MMDの環境構築で詰んでるので詳しい人教えて……',
'幅広く技術周りが好きです。今までは広く浅くみたいなところがあったのですが、今年からは深く攻めていきたいなーと思ってます！昨年は米国でちょい働いたり新しく始めたギフト系ECが忙しかったりと休学してて同期にあまり知り合いがいないので、気軽に声かけてくれると嬉しいです！ビジネスに限らず最近はセキュリティとか低レイヤーにも興味がありますー！',
'いつも前の方で授業受けてます、よく控え室にいるので一緒にゲームとかしてください！',
'大学からマジックしてます！出身は岡山県です！趣味は遊ぶことと旅行と寝ることです！全然話したことのない人ばかりなので、是非仲良くしてください〜！',
'石川県出身です。サッカーが好きです。よろしくお願いします。',
'横浜から通ってます。',
'音楽と旅行が好きです。ベースが弾けます。イベ長です。よろしくお願いします。',
'吹奏楽でトランペットやってます。音楽好きな人是非話しましょう…！あと最近競プロもはじめたので界隈の人色々教えてください…！',
'足は軽めです',
'2Aの時に割とやってたAtCoderを最近再開した(aleutra)のでまた頑張っていきたいところです…',
'一緒に古戦場を走ってくれる人を募集しています。',
'ごろごろしてゲームするだけの人です  PC・PS4とかで遊ぶ人いたらよろしくどうぞ',
'世はグルメ時代',
'特に何も強くないですが音ゲーがちょっとできます。',
'新幹線ユーザーです。ラーメンとか油そばとか好きです。よろしくお願いします。',
'ごちうさが大好き！！！',
'絶起しがち'
];

const icon_array = ['https://drive.google.com/open?id=11NtvfsQNJ2uyaG6CQDbcj_Ck-2bCWXQ2',
'https://drive.google.com/open?id=1cYbr9pi7xzJVXq5Cvd0i_7bsj_8rZJwG',
'https://drive.google.com/open?id=1BHC63T6mqqNGRcXt8_os9_WQQd6Ckv7l',
'https://drive.google.com/open?id=1ueB18DPCgLb1gXoaq7cs5YlvoL-zIROD',
'https://drive.google.com/open?id=177ZnYTrFTzy-fIK_tYQttJKt0vUnStUi',
'https://drive.google.com/open?id=10tD3h2W4pxfkNUwNydxTRANnkfEAxlOm',
'https://drive.google.com/open?id=1iICqHM0fCjKFS6jKE-Q6RSKOF71iiqXx',
'https://drive.google.com/open?id=1bia4Gw3NVLwuKdwBpkLv_Dsa0FzPJ94z',
'https://drive.google.com/open?id=1b1-UOx2pSd6t_Je3zfM9zO1pZuOA_z9f',
'https://drive.google.com/open?id=1u8Fm0E7T46BZAOY5nU95ugxrtfGlIora',
'https://drive.google.com/open?id=1gr2f-P3QyYZdMTvCLLW4m4OyihFbrynQ',
'https://drive.google.com/open?id=1_cTxKoY_JMM6FyviQ1oy2iYpwns_nsDh',
'https://drive.google.com/open?id=176xQZXjvlK_lHR8C22BKssXfmlNLu4Vm',
'https://drive.google.com/open?id=1-BefjmeKILdPAJNW6SL5Zt8XmWI9N1X9',
'https://drive.google.com/open?id=1mLSih5GZKQ-WCqUJnObjBlftix7tvEX-',
'https://drive.google.com/open?id=11dZ-bNw0hJDsh19Qec3HwmgQp5k_9GyT',
'https://drive.google.com/open?id=1O-6j0Uq4tdJ-UF7mr4ECri5NSp74vmez',
'https://drive.google.com/open?id=1irZqIIuVf2pCewTXs1YkshPxYZIP5pMO',
'https://drive.google.com/open?id=1nYYI-x6wwUg6vIUwBuS6Lk1ybLWDZ68O',
'https://drive.google.com/open?id=1NF7_VbLpIDQlOFktvo-WA7fYLqcR1aVh',
'https://drive.google.com/open?id=1b6nftAFGQmmrLGL_OaHkW5BjJA3hMsCn',
'https://drive.google.com/open?id=1wWqSJRLm3T0i_JWTKPfDI-SKrBYFh8zQ',
'https://drive.google.com/open?id=11WDBerqC1tPq_F4ZdgbMF0ch2cIM8U4D',
'https://drive.google.com/open?id=1kgQtHpbTkQmlkw5INKCJo4xNT3ptgu-T',
'https://drive.google.com/open?id=17mOPzUgvYRaDyUYXySMtHR6ySndwi4lm',
'https://drive.google.com/open?id=1m_oDWWz1Xmo7l9cbCIspX8la5ZSCyl21',
'https://drive.google.com/open?id=1948wxH0rgc_VglakRBg4ucx3f-VPoC9z',
'https://drive.google.com/open?id=1Nh5wRWEqFoJwuH60ncf8h59BZQXhrQWa',
'https://drive.google.com/open?id=1GSQtaxzOU5BSssjUCayhbfrW3fF-bbBv',
'https://drive.google.com/open?id=1_pynkqCK0UVkGO35-tHdu-oU9dsBLN6r',
'https://drive.google.com/open?id=1_DHs_aiBhGX2Gc2JHtimDuzIH7J6JjK3',
'https://drive.google.com/open?id=1meLCrOlrmOLATkmH3x5nozSmcLdGI1oP',
'https://drive.google.com/open?id=1GJZk6NqY44wN91lQ7rELnGyG_nOp6ZXs',
'https://drive.google.com/open?id=15HXH8pqwiuNP7owUnNlfV3fX0fC8fWyU',
'https://drive.google.com/open?id=1tJ3Q2aKP7FDKAIUIGZRdx1j7--GqnGYR',
'https://drive.google.com/open?id=1DfrmfmpPRK8qzZLjy-kpfzCpqaUt4JMh',
'https://drive.google.com/open?id=1lYQuPPaGJlX_bejf1dQjSfDzJzuquGMN',
'https://drive.google.com/open?id=1YWsi2Y_GsOLgKy898znjbHoi3GMGHye8',
'https://drive.google.com/open?id=1reqek5R8IIHTAevgbtzkzs7dFdywWI7W',
'https://drive.google.com/open?id=1MSc7lYjzegDI2-CrxvTQ-2ycuzAM77Lq',
'https://drive.google.com/open?id=1XXWljenPb9-7Ntdu-Bg3oNLbE7NMyPJj',
'https://drive.google.com/open?id=1Qm2vPCnsje2zhue0h8JMuKJr9kfkPczm',
'https://drive.google.com/open?id=1-IUs5x5iSO2EsEMktwSe_JZ_1B9F78T_',
'https://drive.google.com/open?id=1GQTKQP0i8k8GeavaoeAK3JmoS6eWavGK',
'https://drive.google.com/open?id=1wtmvtSuP8UuvNlWLcislhhFAq-y925cJ',
'https://drive.google.com/open?id=1RiAFo_VBLYZoU0V1_9t4caj1HPb6YxV5',
'https://drive.google.com/open?id=1OHajv47sWLKSWFj0zvIaYWVikj1hh1YC',
'https://drive.google.com/open?id=1DLiVQa0YIFFAh-F5mSBcCGIAwXQNsnTU',
'https://drive.google.com/open?id=1qOVWF5q2tMucDeKfvwYIHfe212HquOMP',
'https://drive.google.com/open?id=1R-QwDbB-HgQ3QLSJFGxdwta2EceN1oZy',
'https://drive.google.com/open?id=1k9ouDsVF3ngpcGcI6EcQFSHwtxfiehow',
'https://drive.google.com/open?id=1U4z0MTh9R8s7hS9riA1W72U8OSqZNJ08',
'https://drive.google.com/open?id=1Yxxtjf4akohUl4z2l8IM4ok50FLTpjwq',
'https://drive.google.com/open?id=10SvWRiYCuQCInvpsIzJ81EjnGh4z6v8t',
'https://drive.google.com/open?id=1SGJYUReaAG_BIh7-KRydfR2t1TLNDwBG',
'https://drive.google.com/open?id=1-NdZjJRA9XVZqgukqHgXdyiU_Nz0VZEC',
'https://drive.google.com/open?id=1SNodbcsoX-IJBLJet8Edfo_zXry35dqu',
'https://drive.google.com/open?id=11DJp2LVXkgYVTy1GjL2w4Am28X-eMs8h',
'https://drive.google.com/open?id=1S0Vn1mWTuxBcfyqyQVKs3SGksqq0Dv6O',
'https://drive.google.com/open?id=16-PlgmNW-QKtDLEmWV6Sm4Bw1MeSIvYh',
'https://drive.google.com/open?id=10_Ver-hxObfFWE7zUL3Rbgc3AAljCOwK',
'https://drive.google.com/open?id=1gsqX4jBK6vtEcChugzAy9wrlttCfypMm',
'https://drive.google.com/open?id=1fTtYG0oKi-n7tRxwwDVO9v7jTRu-zq2z',
'https://drive.google.com/open?id=1qH7vGY-qg_Dq7aofRZxukXJqq9VTcc7I',
'https://drive.google.com/open?id=1pGbtgz70WgCkcZZglQC2msGW26YiAK_l',
'https://drive.google.com/open?id=1mT3kT_uJOFCsRFaD2iSaGdDRg-pEyTZj',
'https://drive.google.com/open?id=11vUxVY2jX9UwxoVyHpEhS_nV16GzYjMd',
'https://drive.google.com/open?id=13QrOjWZP5vV1KNPLj4pIfVRcck9ae562',
'https://drive.google.com/open?id=1hnUin4NZVmlsNlkSuQ0KmDurOwsErYGQ',
'https://drive.google.com/open?id=1tha0LKRwQxqBcxY4kRuZP-_Mae_T6p4d',
'https://drive.google.com/open?id=1ED_T27cGVhU2aofCju6gYu4fzRyt6Ff1',
'https://drive.google.com/open?id=18XTsnBnc6Ec7bZoD6HsGFoRpgX7BmxM7',
'https://drive.google.com/open?id=1gHfA_xcUUYAfEtnUx9ReMH3SAOlDdRj5',
'https://drive.google.com/open?id=1cj2dgWM3NceXZAwan-6OoIi_p8FMT1_A',
'https://drive.google.com/open?id=1O5HPPPqb6INqLP8A0xHTkBaOwNqlSpa-',
'https://drive.google.com/open?id=1rrIwUcA7sY2cSk78eg9nGF9BKqdn1fLR',
'https://drive.google.com/open?id=1Hq5Ae41p9rCrnPsm1hs-nOc8UoN5vGMF',
'https://drive.google.com/open?id=18uUMseoa7PTx2eefaSY0bAfcdQ4Qh-g4',
'https://drive.google.com/open?id=1TfnSJhi-F5ztPgAvzXSfp7pji2J2q-FD',
'https://drive.google.com/open?id=1AuFx1CAQa_ysGkdRa5FwIl9trV12E3d-',
'https://drive.google.com/open?id=1qh6uBlY4YVttZ3xvSSXnY0l24IANOs3M',
'https://drive.google.com/open?id=1md6bSV-LLL04UPr-uOVEYAgKr3zSVzvL',
'https://drive.google.com/open?id=1jsOdTMROWpRx90oUnVoiQp4hFImyPrze',
'https://drive.google.com/open?id=1oggjUcPe835lYL204YXC415vfedio17C',
'https://drive.google.com/open?id=1h9Mv7o8szPJ9s0-Z6fHg4-xLaQJbY1N2',
'https://drive.google.com/open?id=1tySj-oEhufgPtKnjUjc9HUOue8NJ4V-G',
'https://drive.google.com/open?id=16arjfEoyG77G9SDsR8F5zKxhFWJOZF0k',
'https://drive.google.com/open?id=1uuudq1lqO25p5083WSiHIBg0Oh9XHTNa',
'https://drive.google.com/open?id=1HxKIk5R1ISqi1EeHr97NRffom8wc39Et',
'https://drive.google.com/open?id=1UggjFEXkvH3gz_C1JrgekyKSwknHlFPk',
'https://drive.google.com/open?id=1275cwkE3wRUEl47xFkHiXyEkrjQvb8DT',
'https://drive.google.com/open?id=1M7l_Egvnsvvhn4STdYvb4G6K7arwQ2Hw',
'https://drive.google.com/open?id=1WqzGnafp2X9D2GJRZXFdIDBcpC3-vseM',
'https://drive.google.com/open?id=19bfmhewAaE1P8FjLilHSkkMaMdwuZAn_',
'https://drive.google.com/open?id=1lVGQntKMG5i_Fr6w1vdqyC5_XECL0cmO',
'https://drive.google.com/open?id=1Kv1tbc6GY6cSue0-klWuapowQdAnYsIp',
'https://drive.google.com/open?id=1EAjNnSbpEwCI6AwjO-QuzrMimLlHFYBq',
'https://drive.google.com/open?id=1SbBoHuvp4m1Ul5zoD6lH5yTiwBm-sI0L',
'https://drive.google.com/open?id=1e0Z4mkymyNOGbUR_Mg81jHiRyQ6JoMFi',
'https://drive.google.com/open?id=1tcO9SnRcSlGq7Au5j9CTLi8LnLXYSZfd',
'https://drive.google.com/open?id=1VZHbtJ_6JoHZeVMYs4PBD2pX0QKRB7Ji',
'https://drive.google.com/open?id=103WoG4elm4oELcKShByQfYVcLBnKxryd',
'https://drive.google.com/open?id=10696nXtL-jAMX12LZYiqduSGoxygz1BC']

//GoogleDriveのURLを画像として取得可能な形にする
for(let i=0; i<icon_array.length; i++){
  icon_array[i] ="http://drive.google.com/uc?export=view&id=" + icon_array[i].slice("https://drive.google.com/open?id=".length);
}

//
// document.body.appendChild(name);
//
// document.getElementById('target').addEventListener('click', function(){
//   document.getElementById('target').style.background = 'pink';
// });
//
// for(let i = 0; i<10; i++){
//   const name = document.createElement("div");
//   document.body.appendChild(name);
// }

// プロフィール画像の作成

for(let i = 0; i < name_array.length ; i++){
  const icon = document.createElement("img");
  icon.src = icon_array[i];
  icon.classList.add('icon');
  document.body.appendChild(icon);
  //名前の表示
  const name = document.createElement("div");
  name.textContent = name_array[i];
  name.classList.add('name');
  document.body.appendChild(name);

  //あだ名の表示
  const nickname = document.createElement("div");
  nickname.textContent = nickname_array[i];
  nickname.classList.add('nickname');
  document.body.appendChild(nickname);

  //プロフィールの表示
  const message = document.createElement("div");
  message.textContent = message_array[i];
  message.classList.add('message');
  document.body.appendChild(message);

  console.log()
}
